---
title: "02_probe_wise_ewas"
author: "Puvvula"
date: "2023-07-05"
output: pdf_document
---
#https://nbis-workshop-epigenomics.readthedocs.io/en/latest/content/tutorials/methylationArray/Array_Tutorial.html

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor, CpGassoc, future, future.apply, appliedepi)
processed<- "~/Documents/methylation_pilot/processed/"
```

#CMBC analysis
```{r, message=FALSE, warning=FALSE}
#load one of these files: cbmc_processed.rda; fp_processed.rda; mp_processed.rda

load(paste0(processed, "cbmc_processed.rda"))
dat_chem_qn <- read_csv("~/Documents/methylation_pilot/exp_processed/chem_qn_fin.csv")

dat_pheno <- cbmc_pheno |>
  left_join(dat_chem_qn, by = "participant_id") |>
  mutate(across(where(is.character), as.factor)) |>
  filter(if_any(22:59, ~ !is.na(.))) |>
  mutate(across(22:59, ~ log10(. + 0.000001)))
```

#check sequence of gsm_id from preprocessed and pheno data
```{r}
bVals <- bVals[, match(dat_pheno$gsm_id, colnames(bVals)), drop = FALSE]
mVals <- mVals[, match(dat_pheno$gsm_id, colnames(mVals)), drop = FALSE]

setdiff(dat_pheno$gsm_id, colnames(bVals))
setdiff(dat_pheno$gsm_id, colnames(mVals))

nCpG = dim(bVals)[1]
```

# beta input dataset transforms into m values set in the function
```{r}
#cell types for CMBC: "CD8T", "CD4T", "NK", "Bcell", "Mono", "Gran", "nRBC"
ewas_loop_pll(exposures= c("x24_dcp", "x25_dcp", "bp_3", "bpa", "bps",
                           "e_pb", "m_pb", "p_pb",
                           "mecptp", "mehhtp", "monp", "m_bp", "m_bz_p", "m_cnp", "m_cop", "m_ep", "mi_bp",
                           "fluo2", "nap1", "nap2", "phen1", "phen4", "phen9", "phen23", "pyr1"),
              covariates= c("mom_age", "mom_race", "mom_edu", "pgtob", "bmi", "sex",
                            "cell_fp_1", "cell_fp_2", "cell_fp_3", "cell_fp_4", "cell_fp_5"),
              bVals_list = list(bVals),
              bVals_names = list("mp"),
              dat_pheno = dat_pheno,
              outputFolder = "~/Documents/methylation_pilot/mp_results")
```

#EWAS summary
```{r}
ewas_summary <- function(folder_path) {
    # Get a list of CSV files in the specified folder
    files <- list.files(path = folder_path, pattern = "\\.csv$", full.names = TRUE)
    
    # Initialize an empty data.frame to store results
    result_df <- data.frame(File_Name = character(0),
                            Num_Observations_FDR_lt_0.05 = numeric(0),
                            CPG_Labels_FDR_lt_0.05 = character(0),
                            stringsAsFactors = FALSE)
    
    for (file_path in files) {
        # Read the file
        data <- read.csv(file_path)
        
        # Filter observations with FDR < 0.05
        filtered_data <- data[data$FDR < 0.05, ]
        
        # Get the count of observations with FDR < 0.05
        count_fdr_lt_0.05 <- nrow(filtered_data)
        
        # Get the list of CPG.Labels with FDR < 0.05 as a comma-separated string
        cpg_labels_lt_0.05 <- paste(filtered_data$CPG.Labels, collapse = ", ")
        
        # Extract file name from the path
        file_name <- basename(file_path)
        
        # Create a data.frame for the current file
        file_result <- data.frame(
            File_Name = file_name,
            Num_Observations_FDR_lt_0.05 = count_fdr_lt_0.05,
            CPG_Labels_FDR_lt_0.05 = cpg_labels_lt_0.05,
            stringsAsFactors = FALSE
        )
        
        # Append the results for the current file to the overall result
        result_df <- rbind(result_df, file_result)
    }
    
    # Return the resulting dataframe
    return(result_df)
}
```


